// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class Application
{
    [Key]
    public int ApplicationID { get; set; }

    public int ApplicantPersonID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ApplicationDate { get; set; }

    public int ApplicationTypeID { get; set; }

    /// <summary>
    /// 1-New 2-Cancelled 3-Completed
    /// </summary>
    public byte ApplicationStatus { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastStatusDate { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal PaidFees { get; set; }

    [ForeignKey("ApplicantPersonID")]
    [InverseProperty("Applications")]
    [JsonIgnore]
    public virtual Person ApplicantPerson { get; set; }

    [ForeignKey("ApplicationTypeID")]
    [InverseProperty("Applications")]
    [JsonIgnore]
    public virtual ApplicationType ApplicationType { get; set; }

    [InverseProperty("ReleaseApplication")]
    [JsonIgnore]
    public virtual ICollection<DetainedLicense> DetainedLicenses { get; set; } = new List<DetainedLicense>();

    [InverseProperty("Application")]
    [JsonIgnore]
    public virtual ICollection<InternationalLicense> InternationalLicenses { get; set; } = new List<InternationalLicense>();

    [InverseProperty("Application")]
    [JsonIgnore]
    public virtual ICollection<License> Licenses { get; set; } = new List<License>();

    [InverseProperty("Application")]
    [JsonIgnore]
    public virtual ICollection<LocalDrivingLicenseApplication> LocalDrivingLicenseApplications { get; set; } = new List<LocalDrivingLicenseApplication>();

    [InverseProperty("RetakeTestApplication")]
    [JsonIgnore]
    public virtual ICollection<TestAppointment> TestAppointments { get; set; } = new List<TestAppointment>();
}