// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class ApplicationType
{
    [Key]
    public int ApplicationTypeID { get; set; }

    [Required]
    [StringLength(150)]
    public string ApplicationTypeTitle { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal ApplicationFees { get; set; }

    [InverseProperty("ApplicationType")]
    [JsonIgnore]
    public virtual ICollection<Application> Applications { get; set; } = new List<Application>();
}