// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DLMS.Core.Models;

public partial class DetainedLicense
{
    [Key]
    public int DetainID { get; set; }

    public int LicenseID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime DetainDate { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal FineFees { get; set; }

    public bool IsReleased { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime? ReleaseDate { get; set; }

    public int? ReleaseApplicationID { get; set; }

    [ForeignKey("LicenseID")]
    [InverseProperty("DetainedLicenses")]
    public virtual License License { get; set; }

    [ForeignKey("ReleaseApplicationID")]
    [InverseProperty("DetainedLicenses")]
    public virtual Application ReleaseApplication { get; set; }
}