// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DLMS.Core.Models;

public partial class Driver
{
    [Key]
    public int DriverID { get; set; }

    public int PersonID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime CreatedDate { get; set; }

    [InverseProperty("Driver")]
    public virtual ICollection<InternationalLicense> InternationalLicenses { get; set; } = new List<InternationalLicense>();

    [InverseProperty("Driver")]
    public virtual ICollection<License> Licenses { get; set; } = new List<License>();

    [ForeignKey("PersonID")]
    [InverseProperty("Drivers")]
    public virtual Person Person { get; set; }
}