// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class InternationalLicense
{
    [Key]
    public int InternationalLicenseID { get; set; }

    public int ApplicationID { get; set; }

    public int DriverID { get; set; }

    public int IssuedUsingLocalLicenseID { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime IssueDate { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime ExpirationDate { get; set; }

    public bool IsActive { get; set; }

    [JsonIgnore]
    [ForeignKey("ApplicationID")]
    [InverseProperty("InternationalLicenses")]
    public virtual Application Application { get; set; }

    [JsonIgnore]
    [ForeignKey("DriverID")]
    [InverseProperty("InternationalLicenses")]
    public virtual Driver Driver { get; set; }

    [JsonIgnore]
    [ForeignKey("IssuedUsingLocalLicenseID")]
    [InverseProperty("InternationalLicenses")]
    public virtual License IssuedUsingLocalLicense { get; set; }
}