// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class License
{
    [Key]
    public int LicenseID { get; set; }

    public int ApplicationID { get; set; }

    public int DriverID { get; set; }

    public int LicenseClass { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime IssueDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpirationDate { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal PaidFees { get; set; }

    public bool IsActive { get; set; }

    /// <summary>
    /// 1-FirstTime, 2-Renew, 3-Replacement for Damaged, 4- Replacement for Lost.
    /// </summary>
    public byte IssueReason { get; set; }

    [ForeignKey("ApplicationID")]
    [InverseProperty("Licenses")]
    [JsonIgnore]
    public virtual Application Application { get; set; }

    [InverseProperty("License")]
    [JsonIgnore]
    public virtual ICollection<DetainedLicense> DetainedLicenses { get; set; } = new List<DetainedLicense>();

    [ForeignKey("DriverID")]
    [InverseProperty("Licenses")]
    [JsonIgnore]
    public virtual Driver Driver { get; set; }

    [InverseProperty("IssuedUsingLocalLicense")]
    [JsonIgnore]
    public virtual ICollection<InternationalLicense> InternationalLicenses { get; set; } = new List<InternationalLicense>();

    [ForeignKey("LicenseClass")]
    [InverseProperty("Licenses")]
    [JsonIgnore]
    public virtual LicenseClass LicenseClassNavigation { get; set; }
}