// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class LocalDrivingLicenseApplication
{
    [Key]
    public int LocalDrivingLicenseApplicationID { get; set; }

    public int ApplicationID { get; set; }

    public int LicenseClassID { get; set; }

    [ForeignKey("ApplicationID")]
    [InverseProperty("LocalDrivingLicenseApplications")]
    [JsonIgnore]
    public virtual Application Application { get; set; }

    [ForeignKey("LicenseClassID")]
    [InverseProperty("LocalDrivingLicenseApplications")]
    [JsonIgnore]
    public virtual LicenseClass LicenseClass { get; set; }

    [InverseProperty("LocalDrivingLicenseApplication")]
    [JsonIgnore]
    public virtual ICollection<TestAppointment> TestAppointments { get; set; } = new List<TestAppointment>();
}