// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace DLMS.Core.Models;

public partial class TestType
{
    [Key]
    public int TestTypeID { get; set; }

    [Required]
    [StringLength(100)]
    public string TestTypeTitle { get; set; }

    [Required]
    [StringLength(500)]
    public string TestTypeDescription { get; set; }

    [Column(TypeName = "smallmoney")]
    public decimal TestTypeFees { get; set; }

    [InverseProperty("TestType")]
    [JsonIgnore]
    public virtual ICollection<TestAppointment> TestAppointments { get; set; } = new List<TestAppointment>();
}