// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DLMS.Core.Models;

public partial class Test
{
    [Key]
    public int TestID { get; set; }

    public int TestAppointmentID { get; set; }

    /// <summary>
    /// 0 - Fail 1-Pass
    /// </summary>
    public bool TestResult { get; set; }

    [StringLength(500)]
    public string Notes { get; set; }

    [ForeignKey("TestAppointmentID")]
    [InverseProperty("Tests")]
    public virtual TestAppointment TestAppointment { get; set; }
}